Blobstore
anthonyqzhu/step pull request #21
Opened 2020-06-10 20:55 UTC by anthonyqzhu

Add code attaching blobstore URL to comment form

2020-06-10 21:16 UTC, yjennywang requested changes

2020-06-10 21:16 UTC, yjennywang commented on portfolio/src/main/java/com/google/sps/servlets/BlobstoreUploadUrlServlet.java
> +@WebServlet("/blobstore-upload-url")
How about create-image-upload-url (or even -location), to make it clearer what the action is?


This is more personal preference on my part, but I would also suggest referring to Blobstore indirectly (as the image hosting db/server or whatnot) here and in the JS because it's irrelevant to the user that we're using Blobstore (implementation detail). the important thing is that this sets up the upload location.

2020-06-10 21:16 UTC, yjennywang commented on portfolio/src/main/webapp/script.js
> +/* Enact the functions need onload */
How about "Initializes the page"?

2020-06-10 21:16 UTC, yjennywang commented on portfolio/src/main/java/com/google/sps/servlets/BlobstoreUploadUrlServlet.java
> +    response.setContentType("text/html");
does this need to be text/html if you're just returning a URL without any HTML

Maybe this should be returned as json (to use a consistent data format for the servlets)

2020-06-10 21:16 UTC, yjennywang commented on portfolio/src/main/webapp/index.html
>          <input type="text" name="comment-text">
is this text field used any more?

2020-06-10 21:16 UTC, yjennywang commented on portfolio/src/main/webapp/script.js
> +/* Enables the comment form with the blobstore image upload URL */
"Enables" -> "Sets up"

2020-06-10 21:16 UTC, yjennywang commented on portfolio/src/main/webapp/script.js
> +  fetch('/blobstore-upload-url')
I think there might be a race here.

Because promises are asynchronous, I think it would be possible for the user to click the form submission before the blobstore upload url returns and the form is set up, e.g. due to lag.

It may be a bit hard to reproduce, but you could try adding some latency  to your servlet (with a wait/sleep/for loop) and see what happens.

This is a case where you might actually want to make the flow synchronous.

2020-06-10 21:16 UTC, yjennywang commented on portfolio/src/main/webapp/script.js
> +}
What happens if there is a failure in /blobstore-upload-url?

2020-06-10 21:16 UTC, yjennywang commented on portfolio/src/main/webapp/script.js
> +        return response.text();
You can merge these two then functions into one.

response.text() doesn't involve any network calls, so there's no need to use a promise here.

2020-06-10 21:54 UTC, anthonyqzhu commented on portfolio/src/main/webapp/script.js
> +        return response.text();
It seems like it doesn't work when merging the functions. I looked into it a little and it seems like response.text() reads the response stream and also returns a promise - so maybe it is necessary to wait for the .text() call to resolve before using the value?

2020-06-10 21:55 UTC, anthonyqzhu commented on portfolio/src/main/webapp/script.js
> +  fetch('/blobstore-upload-url')
Noted - I changed it to match the example where the form is hidden until the upload url is available

2020-06-10 21:55 UTC, anthonyqzhu commented on portfolio/src/main/webapp/index.html
>          <input type="text" name="comment-text">
Yes I think the idea is to allow text comments along with image uploads at the same time

2020-06-10 21:57 UTC, anthonyqzhu commented on portfolio/src/main/java/com/google/sps/servlets/BlobstoreUploadUrlServlet.java
> +    response.setContentType("text/html");
I'm not sure if this is right but does the type need to be text/html for us to insert it into the action of the form?

2020-06-10 22:19 UTC, yjennywang commented on portfolio/src/main/webapp/index.html
>          <input type="text" name="comment-text">
ah, does the blobstore url handle it?

2020-06-10 22:21 UTC, yjennywang commented on portfolio/src/main/webapp/script.js
> +        return response.text();
ah, my mistake! thanks for looking into this 

Let's pretend that was a trick question. :)

2020-06-10 22:24 UTC, yjennywang commented on portfolio/src/main/java/com/google/sps/servlets/BlobstoreUploadUrlServlet.java
> +    response.setContentType("text/html");
no; you could do text/plain (iirc) or json (in that case you would have to parse it). But again, not a bad thing and possibly more extensible (e.g. if you want to eventually add other metadata, e.g. errors)

2020-06-10 22:24 UTC, yjennywang commented on portfolio/src/main/webapp/script.js
> +        // messageForm.classList.remove('hidden');
hmm, is this supposed to be commented out?

2020-06-10 23:09 UTC, anthonyqzhu commented on portfolio/src/main/webapp/index.html
>          <input type="text" name="comment-text">
Yes the blobstore url passes the request to the data servlet with the information and the image link

2020-06-10 23:10 UTC, anthonyqzhu commented on portfolio/src/main/webapp/script.js
> +        // messageForm.classList.remove('hidden');
I wasnt sure if it was necessary at first but then I uncommented it now

2020-06-10 23:20 UTC, anthonyqzhu commented on portfolio/src/main/webapp/script.js
> +}
Will have to write handling for an error in later

2020-06-10 23:35 UTC, yjennywang commented on portfolio/src/main/java/com/google/sps/servlets/BlobstoreUploadUrlServlet.java
> +    response.setContentType("text/html");
change this to text/plain?

2020-06-10 23:35 UTC, yjennywang approved these changes
approved with one final comment

also, please document TODOs as a github issue or in some way that you won't forget

2020-06-11 15:25 UTC, anthonyqzhu commented on portfolio/src/main/java/com/google/sps/servlets/BlobstoreUploadUrlServlet.java
> +    response.setContentType("text/html");
So I tried using text/plain however then trying to send the POST request led to a 
"This site can’t be reached
localhost refused to connect."
error so I am keeping it as text/html for now

2020-06-11 15:25 UTC, merged